# Generated by Django 4.0.4 on 2022-05-25 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visions', '0002_vision_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vision_to_user',
            options={'verbose_name': 'Liberação de relatório', 'verbose_name_plural': 'Liberação de relatórios'},
        ),
        migrations.AlterModelOptions(
            name='visions',
            options={'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AlterField(
            model_name='vision_to_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de liberação'),
        ),
        migrations.AlterField(
            model_name='vision_to_user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última edição'),
        ),
        migrations.AlterField(
            model_name='vision_to_user',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='vision_to_user',
            name='visionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visions.visions', verbose_name='Relatório'),
        ),
        migrations.AlterField(
            model_name='visions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='visions',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='visions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='É ativo?'),
        ),
        migrations.AlterField(
            model_name='visions',
            name='linkVision',
            field=models.TextField(verbose_name='Url do PowerBI'),
        ),
        migrations.AlterField(
            model_name='visions',
            name='nameVision',
            field=models.CharField(max_length=255, verbose_name='Relatório'),
        ),
        migrations.AlterField(
            model_name='visions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última edição'),
        ),
        migrations.CreateModel(
            name='vision_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de liberação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última edição')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário solicitante')),
                ('visionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visions.visions', verbose_name='Relatório solicitado')),
            ],
            options={
                'verbose_name': 'Solicitação de relatório',
                'verbose_name_plural': 'Solicitação de relatórios',
            },
        ),
    ]
