# Generated by Django 4.0.4 on 2022-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visions', '0004_vision_request_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision_request',
            name='status',
            field=models.CharField(default='pendente', max_length=255, verbose_name='Status'),
        ),
    ]
